name: Build and Push to GCR

on:
  push:
    branches:
      - '**'

jobs:
  # build-linux:
  #   name: Setup, Build, and Publish for Linux
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Setup gcloud CLI
  #       uses: google-github-actions/setup-gcloud@master
  #       with:
  #         service_account_key: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY }} 

  #     - name: Configure docker to use gcloud as credential helper
  #       run: |
  #         gcloud auth configure-docker ${{ secrets.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev

  #     - name: Build image and push to GCR
  #       id: docker_build
  #       uses: docker/build-push-action@v2
  #       with:
  #         file: ./ue-jenkins-buildtools-linux.Dockerfile
  #         push: true
  #         tags: ${{ secrets.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/docker-build-artifacts/ue-jenkins-buildtools-linux:commit-${{ github.sha }}

  build-windows:
    name: Setup, Build, and Publish for Windows
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY }} 

      - name: Configure docker to use gcloud as credential helper
        run: |
          gcloud auth configure-docker ${{ secrets.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev

      - name: Build image and push to GCR
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./ue-jenkins-buildtools-windows.Dockerfile
          push: true
          tags: ${{ secrets.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/docker-build-artifacts/ue-jenkins-buildtools-windows:commit-${{ github.sha }}
