name: ue-jenkins-controller

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: ue-jenkins-controller
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compute short SHA
        run: echo "::set-output name=short_sha::$(git rev-parse --short ${{ github.sha }})"
        id: compute_short_sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GOOGLE_CLOUD_BUILD_ARTIFACT_UPLOADER_SERVICE_ACCOUNT_KEY }} 

      - name: Configure docker to use gcloud as credential helper
        run: |
          gcloud auth configure-docker ${{ secrets.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev

      - name: Build image and push to GCR
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./ue-jenkins-controller
          file: ./ue-jenkins-controller/ue-jenkins-controller.Dockerfile
          push: true
          tags: ${{ secrets.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/docker-build-artifacts/ue-jenkins-controller:commit-${{ steps.compute_short_sha.outputs.short_sha }}
