name: ue-jenkins-ssh-agent

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  build-linux:
    name: Linux - ue-jenkins-ssh-agent
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compute short SHA
        run: echo "::set-output name=short_sha::$(git rev-parse --short ${{ github.sha }})"
        id: compute_short_sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GOOGLE_CLOUD_BUILD_ARTIFACT_UPLOADER_SERVICE_ACCOUNT_KEY }}

      - name: Configure docker to use gcloud as credential helper
        run: |
          gcloud auth configure-docker ${{ secrets.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev

      - name: Build image and push to GAR
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./ue-jenkins-agents/linux/ue-jenkins-ssh-agent
          push: true
          tags: ${{ secrets.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/docker-build-artifacts/ue-jenkins-ssh-agent:commit-${{ steps.compute_short_sha.outputs.short_sha }}-linux

  build-windows:
    name: Windows - ue-jenkins-ssh-agent
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compute short SHA
        run: echo "::set-output name=short_sha::$(git rev-parse --short ${{ github.sha }})"
        id: compute_short_sha

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.14.0"

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_CLOUD_IMAGE_BUILDER_INSTANCE_CONTROLLER_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Build windows-docker-image-builder tool
        run: |
          (cd windows-docker-image-builder && go build -o main .)

      - name: Add service account key to builder workspace
        run: |
          echo '${{ secrets.GOOGLE_CLOUD_BUILD_ARTIFACT_UPLOADER_SERVICE_ACCOUNT_KEY }}' > ue-jenkins-agents/windows/service-account-key.json

      # We zip up the builder-workspace folder, because the cloud image builder will otherwise copy builder-workspace files
      # one-by-one, spending one second per file
      - name: Zip up builder workspace
        run: |
          (cd ue-jenkins-agents/windows && mkdir ../windows-builder-workspace-zipped && zip -r ../windows-builder-workspace-zipped/builder-workspace.zip *)

      - name: Start Windows VM, Build image and push to GAR via said VM, tear down VM
        run: |
          ./windows-docker-image-builder/main \
            -labels type=windows-image-builder \
            -region ${{ secrets.GOOGLE_CLOUD_REGION }} \
            -zone ${{ secrets.GOOGLE_CLOUD_ZONE }} \
            -network image-builder-network \
            -subnetwork image-builder-subnetwork \
            -machineType n1-standard-4 \
            -diskType pd-ssd \
            -diskSizeGb 100 \
            -image windows-cloud/global/images/windows-server-2019-dc-for-containers-v20210212 \
            -workspace-path ue-jenkins-agents/windows-builder-workspace-zipped \
            -serviceAccount build-artifact-uploader@${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}.iam.gserviceaccount.com \
            -command "powershell try { Expand-Archive -Path .\\builder-workspace.zip -DestinationPath .; .\\Build.ps1 -GceRegion ${{ secrets.ARTIFACT_REGISTRY_LOCATION }} -Dockerfile ue-jenkins-ssh-agent-windows.Dockerfile -ImageName ${{ secrets.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/docker-build-artifacts/ue-jenkins-ssh-agent -ImageTag commit-${{ steps.compute_short_sha.outputs.short_sha }}-windows } catch { Write-Error \$_ }"

      - name: Remove builder workspace
        run: |
          rm -rf ue-jenkins-agents/windows-builder-workspace-zipped
