name: ue-jenkins-ssh-agent-vm

on:
  push:
    branches:
      - '**'

jobs:

  build-linux:
    name: Linux - ue-jenkins-ssh-agent-vm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compute short SHA
        run: echo "::set-output name=short_sha::$(git rev-parse --short ${{ github.sha }})"
        id: compute_short_sha

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GOOGLE_CLOUD_BUILD_ARTIFACT_UPLOADER_SERVICE_ACCOUNT_KEY }}

      - name: Upload file to storage
        run: gsutil cp ./ue-jenkins-agent-vms/linux-gce-cos/ue-jenkins-ssh-agent-vm-cloud-config.yaml gs://${{ secrets.GOOGLE_CLOUD_CONFIG_STORAGE_BUCKET }}/ue-jenkins-ssh-agent-vm/cloud-config-commit-${{ steps.compute_short_sha.outputs.short_sha }}.yaml

  build-windows:
    name: Windows - ue-jenkins-ssh-agent-vm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compute short SHA
        run: echo "::set-output name=short_sha::$(git rev-parse --short ${{ github.sha }})"
        id: compute_short_sha

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_CLOUD_IMAGE_BUILDER_INSTANCE_CONTROLLER_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: "Build image"
        id: build_image
        run: |
          IMAGE_NAME=ue-jenkins-ssh-agent-vm-${{ steps.compute_short_sha.outputs.short_sha }}-windows
          cd ue-jenkins-agent-vms/windows && packer build -var project_id=${{ secrets.GOOGLE_CLOUD_PROJECT_ID }} -var zone=${{ secrets.GOOGLE_CLOUD_ZONE }} -var network=image-builder-network -var subnetwork=image-builder-subnetwork -var image_name=${IMAGE_NAME} ue-jenkins-ssh-agent-vm-windows.json
