name: Build and Push to GCR

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY }} 

      - name: Configure docker to use gcloud as credential helper
        run: |
          gcloud auth configure-docker

      - name: Build image and push to GCR
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/ue4-jenkins-master:commit-${{ github.sha }}
